AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template para crear un bucket S3 con configuración básica
  de seguridad y versionado.

Resources:
  MiBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mi-bucket-ejemplo
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: Dev
        - Key: Project
          Value: MiProyecto
