AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Stack completo:
  S3 -> SQS -> Lambda -> Textract -> DynamoDB
  Corregido para evitar EarlyValidation::PropertyValidation

Resources:

  # 1️⃣ SQS Queue
  MiColaSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "textract-queue-${AWS::AccountId}-${AWS::Region}"
      VisibilityTimeout: 60

  # 2️⃣ Permisos para que S3 pueda enviar mensajes a SQS
  S3SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MiColaSQS
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: sqs:SendMessage
            Resource: !GetAtt MiColaSQS.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt MiBucketS3.Arn  # Se resuelve con DependsOn abajo

  # 3️⃣ DynamoDB Table
  MiTablaDynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "TextractResults-${AWS::AccountId}-${AWS::Region}"
      AttributeDefinitions:
        - AttributeName: "FileName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "FileName"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST

  # 4️⃣ IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "TextractLambdaRole-${AWS::AccountId}-${AWS::Region}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: TextractDynamoS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub "${MiBucketS3.Arn}/*"
              - Effect: Allow
                Action:
                  - textract:DetectDocumentText
                Resource: "*"
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                Resource: !GetAtt MiTablaDynamoDB.Arn

  # 5️⃣ Lambda Function
  MiLambdaTextract:
    Type: AWS::Lambda::Function
    DependsOn: LambdaExecutionRole
    Properties:
      FunctionName: !Sub "TextractLambda-${AWS::AccountId}-${AWS::Region}"
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
          import os

          s3 = boto3.client('s3')
          textract = boto3.client('textract')
          dynamodb = boto3.resource('dynamodb')
          table = dynamodb.Table(os.environ['DDB_TABLE'])

          def lambda_handler(event, context):
              for record in event['Records']:
                  bucket = record['s3']['bucket']['name']
                  key = record['s3']['object']['key']

                  response = textract.detect_document_text(
                      Document={'S3Object': {'Bucket': bucket, 'Name': key}}
                  )

                  text = ""
                  for item in response.get('Blocks', []):
                      if item['BlockType'] == 'LINE':
                          text += item['Text'] + "\n"

                  table.put_item(Item={'FileName': key, 'ExtractedText': text})
                  print(f"Processed {key} from {bucket}")

      Environment:
        Variables:
          DDB_TABLE: !Ref MiTablaDynamoDB
      Timeout: 60
      MemorySize: 512

  MiBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "textract-bucket-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        QueueConfigurations:
          - Event: "s3:ObjectCreated:*"
            Queue: !GetAtt MiColaSQS.Arn

    # 8️⃣ Lambda Event Source Mapping (SQS -> Lambda)
  LambdaSQSTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt MiColaSQS.Arn
      FunctionName: !Ref MiLambdaTextract   # ¡CORRECTO!
      BatchSize: 1
      Enabled: true


Outputs:
  BucketName:
    Description: "Nombre del bucket S3"
    Value: !Ref MiBucketS3

  QueueURL:
    Description: "URL de la SQS Queue"
    Value: !Ref MiColaSQS

  LambdaName:
    Description: "Nombre de la Lambda"
    Value: !Ref MiLambdaTextract

  DynamoDBTable:
    Description: "Nombre de la tabla DynamoDB"
    Value: !Ref MiTablaDynamoDB
