AWSTemplateFormatVersion: '2010-09-09'
Description: Bucket S3 con nombre dinámico y versionado

Resources:
  MiBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "mi-bucket-${AWS::AccountId}-${AWS::Region}"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Description: "Nombre del bucket S3"
    Value: !Ref MiBucketS3

  BucketArn:
    Description: "ARN del bucket S3"
    Value: !GetAtt MiBucketS3.Arn
